name: Node Farm Automated Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Project Dependencies
      run: |
        cd 1-node-farm
        npm install slugify

    - name: Install Jest Framework
      run: |
        cd 1-node-farm
        npm install jest --save-dev

    - name: Execute Automated Test Suite
      run: |
        cd 1-node-farm
        npx jest index.test.js